### ISSUE TITLE
Add speaker: Roberto Clapis

### ISSUE THREAD

**Issue by LitoChris** [dmahlow/gophercon.berlin#22]
**Name:** Roberto Clapis

**Talk title:** Practical fuzzing in Go

**Talk description:**
Fuzzing is a commonly used technique among security engineers to find bugs and vulnerabilities in code. Its effectiveness has been proven over time to the point where some projects and companies have mandatory fuzzing coverage.

The most common issue with fuzzing is that it is seen as a low-level arcane practice that does not apply to memory safe languages or that only hackers can use.

With this session I will explain what fuzzing is, why it is useful and how to apply it to your code. I will provide detailed instructions and examples to get the attendees up and running to make their code more robust, correct and trustworthy.

**Bio:** 
Roberto is a Security Engineer at Google. He loves to write, hack, customize, patch and tailor any software that allows him to do so. Roberto has been writing go since 2015 for both structured, complex projects and scripts.

**Social media:**
Twitter: https://twitter.com/@empijei

**Picture:** https://drive.google.com/file/d/1dPgpiedTA6_MCu1Fi6H3N5D6eopq3tnF/view

**Comment by Pisush** [comment]
done
