### ISSUE TITLE
Add speaker: Mauro Stettler 

### ISSUE THREAD

**Issue by LitoChris** [dmahlow/gophercon.berlin#23]
**Name:** Mauro Stettler

**Talk title:** Why you shouldn't write your own memory management in Go

**Talk description:**
The metrics database we work on - Metrictank - powers Grafana Cloud and is also deployed at customer’s premises. In some of these deployments, resource utilisation affects the bottom line. Last year, we kicked off an ambitious project with the main goal of cutting into memory usage and also reducing GC overhead. We would achieve this by managing our own slabs of memory outside the GC’s reach and storing a certain class of strings there in de-duplicated form. Despite the promising idea and the diligent execution, we had not fully considered all trade-offs, which led to the project failing. Instead of reduced memory and infrastructure bills, we’re left with many lessons learned, a handful of interesting open source libraries, an increased appreciation for the GC, and some brewing ideas for revisiting this effort. In this talk, you will learn about all of this.

**Bio:** Professional Go attempter and keyboard torturer

**Social media:**
Twitter: https://twitter.com/@r3pl4y

**Picture:** 
https://drive.google.com/file/d/1ZaigC_loAaA0lLDWSgw92wVngjp6iARI/view

**Comment by Pisush** [comment]
@LitoChris all talks need to have a talk description too.
This specific talk has 2 speakers, both need to be included under the same talk. 
See for example last year's talk: [API Gateway, A Success Story (Joined Talk)](https://www.gophercon.es/#speakers)
