### ISSUE TITLE
CFP

### ISSUE THREAD

**Issue by LitoChris** [dmahlow/gophercon.berlin#4]
Hi Daniel, could you please add CFP to the websites? Below the links for CloudNein and Gophercon. Thank you.

https://www.papercall.io/cloud-nein-2020
https://www.papercall.io/gophercon-eu-2020

**Comment by dmahlow** [comment]
Added CFP go gopphercon.berlin. Cloud.nein is next, though I will probably rewrite the website to not just use images. 🙈

**Comment by LitoChris** [comment]
Thank you!
