### ISSUE TITLE
Workshop 1 description 

### ISSUE THREAD

**Issue by LitoChris** [dmahlow/gophercon.berlin#7]
Hi Daniel! Please add the following description on the GC website; its for workshop #1.
Thank you.

**Title:** 
Web Services in Go

**Summary:**
The Ultimate Service is a class for any Go developer who wishes to learn how to build production ready and well tested web services in Go. This class provides an intensive, comprehensive and idiomatic view of building web services using community accepted idioms and practices.

**Details:**
The class goes beyond just the use of the http package and focuses on building CRUD based services with logging, observability and debugging. We believe this class is perfect for anyone wishing to build production ready, scalable, fast, and highly concurrent web services in Go.

Start/Stop
Logging/Configuration
Web Framework Design
Database Support
Testing Support with Docker
Metrics/Tracing

**Prerequisites:**
Having a background in software development. Experience writing services in any other language is a bonus.

**What a student is expected to learn:**
Everyone is going to be mentally exhausted by the end of the day. We will be challenging every student to think about what they are doing and why. If you want to be a better Go developer, code reviewer, designer and architect, this is the class you want to take.

**Bio:**
William Kennedy is a managing partner at Ardan Labs in Miami, Florida, a mobile, web, and systems development company. He is also a co-author of the book Go in Action, the author of the blog GoingGo.Net, and a founding member of GoBridge which is working to increase Go adoption through diversity.

**Social Links:**
Twitter: https://twitter.com/goinggodotnet
Github: https://github.com/ardanlabs/gotraining
![nvqrzavk_400x400a763](https://user-images.githubusercontent.com/56724108/70703412-67e41e80-1cd0-11ea-9949-d33c2b1c10d5.jpg)

**Comment by LitoChris** [comment]
@Pisush could you please take a look? I still need his social media though.

**Comment by Pisush** [comment]
Once you have the social media added - this can go live
